import type { Request, VoiceMemo, AiSuggestion } from './types'

export const dummyRequests: Request[] = [
  {
    id: 'r1',
    title: 'ダークモード対応',
    description: 'アプリ全体でダークモードを使えるようにしてほしい。夜間の利用が多いため。',
    status: '検討中',
    votes: 42,
    memoIds: ['m1', 'm3'],
    createdAt: '2026-03-15',
  },
  {
    id: 'r2',
    title: 'CSVエクスポート機能',
    description: 'データを CSV 形式でエクスポートしたい。月次レポート作成に使いたい。',
    status: '予定',
    votes: 28,
    memoIds: ['m2'],
    createdAt: '2026-03-10',
  },
  {
    id: 'r3',
    title: 'Slack 連携',
    description: '新しい投稿があったときに Slack に通知してほしい。',
    status: '検討中',
    votes: 19,
    memoIds: ['m4'],
    createdAt: '2026-03-08',
  },
  {
    id: 'r4',
    title: 'モバイル表示の改善',
    description: 'スマートフォンでの一覧表示が見づらいので改善してほしい。',
    status: '完了',
    votes: 35,
    memoIds: ['m5', 'm6'],
    createdAt: '2026-02-20',
  },
  {
    id: 'r5',
    title: '多言語対応',
    description: '英語 UI を追加してほしい。海外ユーザーが増えている。',
    status: '検討中',
    votes: 15,
    memoIds: [],
    createdAt: '2026-03-20',
  },
  {
    id: 'r6',
    title: 'タグ機能の追加',
    description: '要望にタグを付けて分類できるようにしたい。',
    status: '予定',
    votes: 22,
    memoIds: ['m7'],
    createdAt: '2026-03-18',
  },
]

export const dummyMemos: VoiceMemo[] = [
  {
    id: 'm1',
    body: '夜使うとき眩しいのでダークモードほしいです',
    source: 'App Store',
    date: '2026-03-14',
    status: '要望化済み',
    linkedRequestId: 'r1',
  },
  {
    id: 'm2',
    body: 'データのエクスポートってできますか？CSV で出力したいんですが',
    source: 'DM',
    date: '2026-03-09',
    status: '要望化済み',
    linkedRequestId: 'r2',
  },
  {
    id: 'm3',
    body: 'ダークモード対応してほしい！目が疲れます',
    source: 'X',
    date: '2026-03-12',
    status: '要望化済み',
    linkedRequestId: 'r1',
  },
  {
    id: 'm4',
    body: 'Slackに通知飛ばせると便利そう',
    source: 'Discord',
    date: '2026-03-07',
    status: '要望化済み',
    linkedRequestId: 'r3',
  },
  {
    id: 'm5',
    body: 'iPhone で見ると表が崩れます',
    source: 'ユーザー投稿',
    date: '2026-02-18',
    status: '要望化済み',
    linkedRequestId: 'r4',
  },
  {
    id: 'm6',
    body: 'スマホだとボタンが押しにくい',
    source: 'App Store',
    date: '2026-02-15',
    status: '要望化済み',
    linkedRequestId: 'r4',
  },
  {
    id: 'm7',
    body: '要望をカテゴリ分けできると嬉しい',
    source: 'GitHub',
    date: '2026-03-17',
    status: '要望化済み',
    linkedRequestId: 'r6',
  },
  {
    id: 'm8',
    body: 'API でデータ取れるようにしてほしい。自動化したいので。',
    source: 'Discord',
    date: '2026-03-25',
    status: '未整理',
  },
  {
    id: 'm9',
    body: '使い方がわかりにくいです。チュートリアルあると嬉しい。',
    source: 'ユーザー投稿',
    date: '2026-03-26',
    status: '未整理',
  },
  {
    id: 'm10',
    body: 'Webhook 対応してくれたら連携しやすいのに',
    source: 'X',
    date: '2026-03-24',
    status: '保留',
  },
  {
    id: 'm11',
    body: 'レスポンスが遅い時がある。特に一覧ページ',
    source: 'DM',
    date: '2026-03-27',
    status: '未整理',
  },
]

export const dummyAiSuggestions: Record<string, AiSuggestion> = {
  m8: {
    summary: 'API によるデータアクセスの要望。開発者向け機能。',
    similarRequests: ['CSVエクスポート機能', 'Slack 連携'],
    recommendedAction: '「API 公開」として新規要望を作成することを推奨',
  },
  m9: {
    summary: 'オンボーディング・チュートリアルの改善要望。',
    similarRequests: [],
    recommendedAction: '「チュートリアル追加」として新規要望を作成',
  },
  m10: {
    summary: 'Webhook 連携の要望。Slack 連携と関連性あり。',
    similarRequests: ['Slack 連携'],
    recommendedAction: '既存の「Slack 連携」要望に紐づけるか、統合を検討',
  },
  m11: {
    summary: 'パフォーマンスに関する報告。一覧ページの速度問題。',
    similarRequests: [],
    recommendedAction: 'パフォーマンス改善の要望を新規作成',
  },
}
